export const GIRL_ICON = "GIRL";
export const BOY_ICON = "BOY";
export const ALPACA_ICON = "ALPACA";
export const KNIGHT_ICON = "KNIGHT";

export const FOLLOW_AVATAR_BUTTON = "FOLLOW_AVATAR_BUTTON";
export const MAKE_REVIEW_BUTTON = "MAKE_REVIEW_BUTTON";
export const CREATE_CHALLENGE_BUTTON = "CREATE_CHALLENGE_BUTTON";
export const CREATE_ONLINE_BATTLE_BUTTON = "CREATE_ONLINE_BATTLE_BUTTON";

export const CHOOSE_AVATAR_COMPONENT = "CHOOSE_AVATAR_COMPONENT";
export const REVIEWS_HOMEPAGE_COMPONENT = "REVIEWS_HOMEPAGE_COMPONENT";
export const SIDEBAR_COMPONENT = "SIDEBAR_COMPONENT";

export const CHALLENGES_PAGE = "CHALLENGES_PAGE";
