export const GIRL_ICON = "GIRL";
export const BOY_ICON = "BOY";
export const ALPACA_ICON = "ALPACA";
export const KNIGHT_ICON = "KNIGHT";

export const CHOOSE_AVATAR_COMPONENT = "CHOOSE_AVATAR_COMPONENT";
export const REVIEWS_HOMEPAGE_COMPONENT = "REVIEWS_HOMEPAGE_COMPONENT";
export const SIDEBAR_COMPONENT = "SIDEBAR_COMPONENT";
